Music_App/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:create, :new, :show, :index]
  resource :session, only: [:create, :destroy, :new]
  resources :bands
end
 

Music_App/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Music_App/app/models/band.rb
class Band < ApplicationRecord
    validates :name, presence: true
end

Music_App/app/models/user.rb
class User < ApplicationRecord
    attr_reader :password
    before_validation :ensure_session_token

    validates :email, presence: true, uniqueness: true
    validates :password_digest, presence: true
    validates :session_token, presence: true, uniqueness: true
    validates :password, length: { minimum: 6, allow_nil: true}

    def self.generate_session_token
        SecureRandom::urlsafe_base64
    end

    def reset_session_token!
        self.session_token = User.generate_session_token
        self.save!
        self.session_token
    end

    def ensure_session_token
        self.session_token ||= User.generate_session_token
    end

    def password=(password)
        @password = password
        self.password_digest = BCrypt::Password.create(password)
        #self._ calls a setter method defined for us in ActiveRecord
    end

    def is_password?(password)
        pass_check = BCrypt::Password.new(self.password_digest)
        pass_check.is_password?(password)
    end

    def self.find_by_credentials(email,password)
        user = User.find_by(email: email)
        if user && is_password?(password)
            user
        end
        nil
    end

end

Music_App/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :login_user!
    helper_method :current_user
    helper_method :logged_in?
    #write login, logout, logged_in? methods in here
    def login_user!(user)
        #what happens when we log in a user?
            #reset session token
        session[:session_token] = user.reset_session_token!
    end

    def logged_in?
        #check if user exists or not
        !!@current_user
    end

    def logout_user
        #set session token to nil
        session[:session_token] = nil
    end

    def current_user
        @current_user = User.find_by(session_token: session[:session_token])
    end

end

Music_App/app/controllers/bands_controller.rb
class BandsController < ApplicationController

    def index
        @bands = Band.all
        render :index
    end

    def create
        @band = Band.new(band_params)
        if @band.save
            redirect_to band_url(@band)
        else
            render json: 'That band do not exist'
        end
    end

    def new
        @band = Band.new
        render :new
    end

    def edit
        @band = Band.find(params[:id])
        render :edit
    end

    def show
        @band = Band.find(params[:id])
        render :show
    end

    def update
        @band = Band.find(params[:id])
        if @band.update_attributes(band_params)
            redirect_to band_url(@band)
        else
            render json: "something went wrong"
        end
    end

    def destroy
        @band = Band.find(params[:id])
        @band.destroy
        redirect_to bands_url
    end

    def band_params
        params.require(:band).permit(:name)
    end
end

Music_App/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    
    def new
        render :new
    end

    def create
        @user = User.find_by_credentials(params[:user][:email], params[:user][:password])
        if user
            login_user!(@user)
            redirect_to user_url(@user)
        else
            render json: "sorry that didn't work, try again"
        end
    end

    def destroy
        logout_user
        redirect_to new_user_url
    end

end

Music_App/app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index
        User.all
        render :index
    end

    def create
        @user = User.new(user_params)
        if @user.save
            login_user!(@user)
            redirect_to user_url(@user)
        else
            render json: "sorry that didn't work, try again"
        end
    end

    def show
        # @user = User.find_by_credentials(params[:users][:email], params[:users][:password])
        @user = User.find(params[:id])
        render :show
    end

    def new
        @user = User.new
        render :new
    end

    def user_params
        params.require(:user).permit(:email, :password)
    end

end

Music_App/app/helpers/application_helper.rb
module ApplicationHelper
end

Music_App/app/helpers/bands_helper.rb
module BandsHelper
end

Music_App/app/helpers/sessions_helper.rb
module SessionsHelper
end

Music_App/app/helpers/user_helper.rb
module UserHelper
end

Music_App/app/views/bands/edit.html.erb
<h1>Rename Band!</h1>

<form action="<%=bands_url%>" method="POST">
    <input type="hidden" name="_method" value="PATCH">
    <input 
    type="hidden" 
    name="authenticity_token" 
    value="<%= form_authenticity_token %>">
    
    <label for="email">Name</label>
    <input type="text" name="band[name]" id="name"><%=band.name%><br>

    <br><br><button href="band_url">Rename Band!</button>
</form>

Music_App/app/views/bands/index.html.erb
<h1>ALL DEM BANDS</h1>
<button id="add-band" href="<%=new_band_url%>">Add a Band!</button><br>
<body>
        <% @bands.each do |band| %> <br>
        <a id="band-list" href="<%=band_url(band)%>"><%=band.name%></a>
        <% end %>
</body>

Music_App/app/views/bands/new.html.erb
<h1>Create New Band!</h1>

<form action="<%=bands_url%>" method="POST">
    <input 
    type="hidden" 
    name="authenticity_token" 
    value="<%= form_authenticity_token %>">
    
    <label for="email">Name</label>
    <input type="text" name="band[name]" id="name"><br>

    <br><br><button href="band_url">Register Band!</button>
</form>

Music_App/app/views/bands/show.html.erb
<h1><%=@band.name%>'s' Page</h1>
<body>
    <p>This is <%=@band.name%>'s Page</p>

    <button href="<%=bands_url%>">Back to All Bands</button>
</body>

Music_App/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header>MUSIC APP</header>

    <div id="log-buttons">
      <%if logged_in? %>
        <button href="<%=new_user_url%>">Log Out</button>
      <%else%>
        <button href="<%=new_session_url%>">Log In</button>
        <button href="<%=new_user_url%>">Sign Up</button>
      <%end%>
    </div>

  <body>
    <%= yield %>
  </body>
</html>

Music_App/app/views/users/new.html.erb
<h1>Create New User</h1>

<form action="<%=users_url%>" method="POST">
    <input 
    type="hidden" 
    name="authenticity_token" 
    value="<%= form_authenticity_token %>">
    
    <label for="email">Email</label>
    <input type="text" name="user[email]" id="email"><br>

    <label for="email">Password</label>
    <input type="password" name="user[password]" id="password">

    <br><br><button href="user_url">Sign Up!</button>
</form>

Music_App/app/views/users/show.html.erb
<h1>User Page</h1>
<body>
    <p>This is <%=@user.email%>'s User Page</p>
</body>